language: node_js
node_js:
  - 'stable'
dist: trusty
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bevcapitaltest;'
install: 
  - yarn install
before_script:
  - yarn global add typescript -D
  - yarn global add typings -D
script: yarn test
after_success: yarn coverage