language: node_js
node_js:
  - 'stable'
dist: trusty
services:
  - mysql
  - redis-server
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bevcapitaltest;'
install:
  - yarn install
script: yarn test
after_success: yarn coverage
