language: node_js
node_js:
  - 'stable'
dist: trusty
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bevcapitaltest;'
install: 
  - yarn global add typescript
  - yarn install
script: yarn test
after_success: yarn coverage